name: reference_parser_ssai
description: >-
  Fork of reference_parser. Additional parameters for existing parsers and function for returning original string with refs.
version: 1.0.7
homepage: https://github.com/KLMcCaughan/reference_parser_ssai
issue_tracker:  https://github.com/KLMcCaughan/reference_parser_ssai/issues
environment:
  sdk: '>=2.12.0 <4.0.0'
dependencies:
  html: ^0.15.0
  http: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.4
